services:
  sup-backend:
    platform: linux/x86_64
    image: glekovkirillll/backend:latest
    container_name: sup-backend
    ports:
      - "8080:80"
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=sup_db
      - DB_PORT=5432
      - DB_DATABASE=sup_backend_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=17263544
    depends_on:
      - sup_db
    command: ["sh", "-c", "composer install --no-dev --optimize-autoloader && php artisan migrate && php artisan serve --host=0.0.0.0"] #при первом запуске добавить после миграции --seed && php artisan key:generate
    networks:
      - sup-network

  sup_db:
    image: postgres:15
    container_name: sup_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 17263544
      POSTGRES_USER: postgres
      POSTGRES_DB: sup_backend_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sup-network

volumes:
  pgdata:

networks:
  sup-network:
    driver: bridge
